# .streamlit/secrets.toml

[connections.ffpe_gsheets]
spreadsheet= "https://docs.google.com/spreadsheets/d/18WNJFahK-IlF8yqIsYkL-yoB1Wyc4cO5uKeDngAkkXs/edit"

[gcp_service_account]
type = "service_account"
project_id = "ravits-lab-paraffin-blocks"
private_key_id = "e254d6aa1b193eda00c0dd4a550d1f2edd7e8f49"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC/v18DJRyqh8Fe\n+ba79sj6shMHNGkgnz6/8t7w/6OBIfAA7kyds6BwaN2Yx44X66g/cg0MyM7tLnOp\n6MNXvQFXNVhzHZgEO2rImBm8NM4TNDqGLjhETyk/vMrclqLXpZ39sG6u7dCXdBqb\nzAmdTjCdgqcFZZCdx1UnJcjDdA/fOFsVH0nn8CpqoBiZ6MetEzfGd0G4qXwt/DAZ\n7F8Bn7YCJbCqLncGo+6FNJL826YJEd7l7ddf/0ie6sCeMl2uBx5yllT6bRudq3x8\nKtnGrg0YkVWajerhCNrDwv47Z1jKkNqKgWv7Dvn2D4kDzsAAsmfzxaolyJazWh4A\n3l++Ww0hAgMBAAECggEAAcoURNzqcM+HXe+SqSM3E5U1WioLsCIPgS19oM2wxrVW\nLtHBVhwK5C0Vqa7bZe8Iqs+0W3F8Hh7/An8lu6RYiSDgjqTa0CDIgWxmoabsU/Z+\nT8c/IHYB2wIdHj0KYAUBxP3hooqzOlrwO23/Hg7mjWJtPrsIlH+rH2BxtE9KzlcY\nT4fJlwiZ6lo2MNNOiQf/t8434MsdMqbojyjgEtaDt3Rlw751ADNM9o/0U/QLKHM8\npGNUYW0ic221mm65FzzwrhEXXJ9+OrjGFT0SrOzrZ/kqvcX7X9B2pAA9ha8Fe8SN\nHj3UY5TH9m2bdgkQgeYKaaVvHJFpgbA0Jb1eSkyuMwKBgQD73YsqF2JCbnyuWqLq\ng0iUgnjGJcmGhN6RvKaQ5hvesMihgWwokmeMN9eX9Ph02O5x8wu/5WulaAhoxBhY\nsPbelmtb3T8b7LwoBEYI+CUZSrnWBF1kg0GCY2D6B2o1FYlqN9eZJ8PvwjaBN6S0\nC+yvxFVRTFcFUj8nIfCngX/2vwKBgQDC5S8ipXAYLWgCRfce7MDxHtCKfo2JwHzs\n7Y/ke/Y0jiv/wwo+CJHKV4DnuAofJ9pBHNM9OUDZ5yL4n98gfmxCNpH07BMiN9ZT\nmJqKf04ZIf6R8I1XQ+aAMVkVvNj4Og1vt0t96HfSbOIsDAYDOqrubWTGoxuC/F8s\nL6w/H/rUHwKBgQCSRLsJGsNpqRineOOcJdoExTC2gkNi588J+/EPvVL6JNifUrYp\nabzQ5a1DBnU0BreTXX65VtcJHD2l+hvZhgwYgGqg0wBPi1BKPREfLFz/LzJ1Y9uI\n/+EPg/9RtPStF3DSStPekgVsO/HDYTk5hqNSAEc8C4WOBZG/fCpyXPafqQKBgHp1\nfQ98+hkG9tJu2d7hjj4zSX+sEw0aGKTahE5hoYrWRkk3aQkfY1PLdaCjoCCBbv74\nuLZAckI4nF2yPoXxSd604TMO3triUNZIDdq2MQFTvdw/VOAfNwcXes1Q0tftyiGG\n/3VGi3t5lQduKpz+0QZtUCQLuq6sGrTt44HqezWrAoGAFYPvvaPRrkm91FuSobrf\ng/RqzyCnloknIaaOpkkwgiIfjS4eV6eebXxZQ5ogPxuQ0D6gmybmrSKv0g8UVwiI\nsu4ESPgSBrF1lHgQEqnc6p5vE8ZMtT8i32dqeuJgffx1YkWdrzDLW/SnDQZDKyzI\ntU5cnCiJecrqy6gkCP0mF5A =\n-----END PRIVATE KEY-----\n"""
client_email = "streamline-reader@ravits-lab-paraffin-blocks.iam.gserviceaccount.com"
client_id = "109128003189797846248"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "http://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamline-reader%40ravits-lab-paraffin-blocks.iam.gserviceaccount.com"


[app_credentials]
hashed_password= "$2b$12$/p0FJC2UaOuewoXVElviyOvMwEpl9MZFyNd14oegpf.INPWDKd8Wy"

